const ALL_PERMISSIONS = [
    "READ_USERS",
    "READ_USER",
    "UPDATE_USER",
    "DELETE_USER",
    "CREATE_COURSE",
    "READ_COURSE",
    "READ_COURSES",
    "CREATE_SUBMISSION",
    "READ_SUBMISSION",
    "READ_SUBMISSIONS",
    "DELETE_SUBMISSION",
    "CREATE_COURSESREQUEST",
    "READ_COURSESREQUESTS",
    "UPDATE_COURSESREQUEST",
    "DELETE_COURSESREQUEST",
    "READ_ALL_COURSESREQUESTS",
    "READ_ALL_PERMISSIONSREQUESTS",
    "READ_PERMISSIONSREQUESTS",
    "CREATE_PERMISSIONSREQUEST",
    "UPDATE_PERMISSIONSREQUEST",
    "DELETE_PERMISSIONSREQUEST",
    "UPDATE_ASSIGNMENT",
    "UPDATE_COURSE",
    "CREATE_ASSIGNMENT"
]

module.exports.ALL_PERMISSIONS = ALL_PERMISSIONS